package com.cplan.creation.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Script entity — the AI-generated screenplay for a project.
 *
 * <p>Status values:
 * <ul>
 *   <li>0 = GENERATING (生成中)</li>
 *   <li>1 = COMPLETED (已完成)</li>
 *   <li>2 = FAILED (失败)</li>
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@TableName("t_script")
public class Script implements Serializable {

    private static final long serialVersionUID = 1L;

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long projectId;

    private Long outlineId;

    /** Full script text generated by LLM. */
    private String content;

    /** LLM model used to generate this script. */
    private String llmModel;

    /** 0=生成中, 1=已完成, 2=失败 */
    private Integer status;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    @TableLogic
    private Integer isDeleted;
}
